- hosts: 'workers, masters'
  become: yes

  tasks:
    - name: create the kube user account
      user: name=kube append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'kube' to use sudo without needing a password
      lineinfile:
        path: /etc/sudoers.d/admin
        create: true
        line: 'kube ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the kube user
      ansible.posix.authorized_key: 
        user: kube 
        state: present
        key: "{{ lookup('file', './id_rsa.pub') }}"
